export { default as completedIcon } from './completedIcon.png'
export { default as deathGraph } from './deathGraph.png'
export { default as dashboard } from './dashboard.png'
export { default as recovered } from './recovered.png'
export { default as vaccines } from './vaccines.jpg'
export { default as rising } from './rising.png'
