export { default as ForgotPassword } from './ForgotPassword'
export { default as WelcomeText } from './WelcomeText'
export { default as SignUpFree } from './SignUpFree'
export { default as LoginForm } from './LoginForm'
export { default as Wrapper } from './Wrapper'
