export { default as ErrorMessage } from './ErrorMessage'
export { default as WelcomeText } from './WelcomeText'
export { default as TextInput } from './TextInput'
export { default as Language } from './Language'
export { default as GreenBtn } from './GreenBtn'
export { default as Wrapper } from './Wrapper'
